EDA Steps and Procedure

In [2]:
import pandas as pd
df = pd.read_csv("D:\\Data Analyst Course\\Train.csv",sep = ',')

In [3]:
# 1.Introduction with our data
df.shape # returns the total number of rows and columns / it is not a function

(8523, 12)

In [9]:
df.info() # it is a function, it shows the data types and the null values
# item weight & outlet size coulmn needs to be analysed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [10]:
df.columns # Return the column names

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [3]:
# 2.1 Top 5 records
df.head(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [4]:
# 2.2.bottom 5 records
df.tail(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [3]:
# 3.Renaming the column names
df_rename=df.rename(columns={'Item_Identifier':'Product Code','Item_MRP':'MRP'}) 
#Assigning a dataframe in a new name is called as shallow copy
df.head(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [20]:
#4.Statiscal description - quick summary of the data
df.describe() # works only for numerical data

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [23]:
#5.Adding the new column
df['Profit Obtained']= df['Item_Outlet_Sales']-df['Item_MRP']
df.head(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Profit Obtained
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,3485.3288
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,395.1536
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,1955.6520
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,550.2850
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,940.8438

In [9]:
#6.Dropping a column - should be done only on approval in real time projects 
df_rename.drop('Item_Type',axis=1,inplace=True)
df_rename.head(5)

,Product Code,Item_Weight,Item_Fat_Content,Item_Visibility,MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [14]:
#7.Setting any column in index
#df.columns
df.set_index('Item_Fat_Content',inplace=True)
# set unique column as index for easier access

In [16]:
# 8.Resetting Index
df.reset_index(inplace = True)

In [17]:
df

,Item_Fat_Content,Item_Identifier,Item_Weight,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,Low Fat,FDA15,9.300,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,Regular,DRC01,5.920,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,Low Fat,FDN15,17.500,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,Regular,FDX07,19.200,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,Low Fat,NCD19,8.930,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,Low Fat,FDF22,6.865,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,Regular,FDS36,8.380,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,Low Fat,NCJ29,10.600,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,Regular,FDN46,7.210,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,Low Fat,DRG01,14.800,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [6]:
9.# setting row with index position
df.iloc[1]

Item_Identifier                          DRC01
Item_Weight                               5.92
Item_Fat_Content                       Regular
Item_Visibility                       0.019278
Item_Type                          Soft Drinks
Item_MRP                               48.2692
Outlet_Identifier                       OUT018
Outlet_Establishment_Year                 2009
Outlet_Size                             Medium
Outlet_Location_Type                    Tier 3
Outlet_Type                  Supermarket Type2
Item_Outlet_Sales                     443.4228
Name: 1, dtype: object

In [13]:
df.iloc[10:15] # fetching inbetween values

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
10,FDY07,11.8,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
11,FDA03,18.5,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530
12,FDX32,15.1,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646
13,FDS46,17.6,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1,2145.2076
15,FDP49,9.0,Regular,0.069089,Breakfast,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192

In [11]:
# 10.selecting subsection of the dataset with loc and iloc
# loc - by labels (column names)
# iloc - by position (by Range)
df.loc[0:5,['Item_Identifier','Item_Weight']]

  Item_Identifier  Item_Weight
0           FDA15        9.300
1           DRC01        5.920
2           FDN15       17.500
3           FDX07       19.200
4           NCD19        8.930
5           FDP36       10.395

In [12]:
# 11.how to drop a row
df.drop(14,axis=0,inplace=True)

In [17]:
#12 If required conditional filtereing
df[df['Item_Weight']>20]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
43,FDC02,21.35,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
89,FDN27,20.85,Low Fat,0.039624,Meat,117.2808,OUT049,1999,Medium,Tier 1,Supermarket Type1,1523.3504
90,FDW20,20.75,Low Fat,0.040421,Fruits and Vegetables,122.1730,OUT010,1998,NaN,Tier 3,Grocery Store,369.5190
122,FDB14,20.25,Regular,0.171939,Canned,92.5120,OUT010,1998,NaN,Tier 3,Grocery Store,186.4240
129,NCP30,20.50,Low Fat,0.032835,Household,40.2822,OUT045,2002,NaN,Tier 2,Supermarket Type1,707.0796
...,...,...,...,...,...,...,...,...,...,...,...,...
8500,NCQ42,20.35,Low Fat,0.000000,Household,125.1678,OUT017,2007,NaN,Tier 2,Supermarket Type1,1907.5170
8503,FDQ44,20.50,Low Fat,0.036133,Fruits and Vegetables,120.1756,OUT035,2004,Small,Tier 2,Supermarket Type1,3392.9168
8512,FDR26,20.70,Low Fat,0.042801,Dairy,178.3028,OUT013,1987,High,Tier 3,Supermarket Type1,2479.4392
8515,FDH24,20.70,Low Fat,0.021518,Baking Goods,157.5288,OUT018,2009,Medium,Tier 3,Supermarket Type2,1571.2880
8517,FDF53,20.75,reg,0.083607,Frozen Foods,178.8318,OUT046,1997,Small,Tier 1,Supermarket Type1,3608.6360

In [19]:
df[(df['Item_MRP']>120)&(df['Item_Weight']>20)] # for more than one conditions

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
43,FDC02,21.35,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
90,FDW20,20.75,Low Fat,0.040421,Fruits and Vegetables,122.1730,OUT010,1998,NaN,Tier 3,Grocery Store,369.5190
148,FDA45,21.25,Low Fat,0.155350,Snack Foods,178.2370,OUT035,2004,Small,Tier 2,Supermarket Type1,529.3110
226,FDW20,20.75,Low Fat,0.024129,Fruits and Vegetables,124.1730,OUT013,1987,High,Tier 3,Supermarket Type1,2956.1520
271,FDS26,20.35,Low Fat,0.089395,Dairy,260.1594,OUT013,1987,High,Tier 3,Supermarket Type1,2093.2752
...,...,...,...,...,...,...,...,...,...,...,...,...
8500,NCQ42,20.35,Low Fat,0.000000,Household,125.1678,OUT017,2007,NaN,Tier 2,Supermarket Type1,1907.5170
8503,FDQ44,20.50,Low Fat,0.036133,Fruits and Vegetables,120.1756,OUT035,2004,Small,Tier 2,Supermarket Type1,3392.9168
8512,FDR26,20.70,Low Fat,0.042801,Dairy,178.3028,OUT013,1987,High,Tier 3,Supermarket Type1,2479.4392
8515,FDH24,20.70,Low Fat,0.021518,Baking Goods,157.5288,OUT018,2009,Medium,Tier 3,Supermarket Type2,1571.2880
8517,FDF53,20.75,reg,0.083607,Frozen Foods,178.8318,OUT046,1997,Small,Tier 1,Supermarket Type1,3608.6360

In [20]:
# 13.Applying function as single column
# syntax:
# lambda arguments:expression 
lambda x:round(x,1) #anonymous function

In [23]:
square =lambda x:x**2
square(75)
# lambda is small anonymous(nameless) function in python

5625

In [26]:
df['Item_Weight'] =df['Item_Weight'].apply(lambda x:round(x,2))
df['Item_Weight']

0        9.30
1        5.92
2       17.50
3       19.20
4        8.93
        ...
8518     6.87
8519     8.38
8520    10.60
8521     7.21
8522    14.80
Name: Item_Weight, Length: 8522, dtype: float64

In [27]:
df

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.87,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.38,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.60,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.21,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.80,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [29]:
#14.Apply funfction on multiple column using lamda function:
df[['Item_Weight','Item_MRP']]=df[['Item_Weight','Item_MRP']].apply(lambda x:x.fillna(x.mean())) 
# fillna function will fill the mean value for the missing values.
df[['Item_Weight','Item_MRP']]

      Item_Weight  Item_MRP
0            9.30  249.8092
1            5.92   48.2692
2           17.50  141.6180
3           19.20  182.0950
4            8.93   53.8614
...           ...       ...
8518         6.87  214.5218
8519         8.38  108.1570
8520        10.60   85.1224
8521         7.21  103.1332
8522        14.80   75.4670

[8522 rows x 2 columns]

In [4]:
#15 sorting method - sorting the particular column
df.sort_values(by = 'Item_Outlet_Sales',ascending = False)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
7188,NCE42,NaN,Low Fat,0.010551,Household,234.9958,OUT027,1985,Medium,Tier 3,Supermarket Type3,13086.9648
5223,FDQ19,NaN,Regular,0.014296,Fruits and Vegetables,242.6512,OUT027,1985,Medium,Tier 3,Supermarket Type3,12117.5600
1450,FDZ20,NaN,Low Fat,0.000000,Fruits and Vegetables,253.0356,OUT027,1985,Medium,Tier 3,Supermarket Type3,11445.1020
4349,FDP33,NaN,Low Fat,0.088840,Snack Foods,254.2672,OUT027,1985,Medium,Tier 3,Supermarket Type3,10993.6896
6541,FDI50,NaN,Regular,0.030693,Canned,228.0352,OUT027,1985,Medium,Tier 3,Supermarket Type3,10306.5840
...,...,...,...,...,...,...,...,...,...,...,...,...
7388,FDQ47,7.155,Regular,0.281510,Breads,33.8874,OUT010,1998,NaN,Tier 3,Grocery Store,35.2874
3053,NCL41,NaN,Low Fat,0.073077,Health and Hygiene,34.3216,OUT019,1985,Small,Tier 1,Grocery Store,34.6216
2571,FDU21,NaN,Regular,0.134328,Snack Foods,35.0558,OUT019,1985,Small,Tier 1,Grocery Store,33.9558
6950,NCR42,9.105,Low Fat,0.064411,Household,33.3900,OUT010,1998,NaN,Tier 3,Grocery Store,33.2900
906,DRK12,9.500,Low Fat,0.000000,Soft Drinks,32.8900,OUT010,1998,NaN,Tier 3,Grocery Store,33.2900

In [16]:
#16.min/max and the index value
min_value=df['Item_MRP'].min()
max_value=df['Item_MRP'].max()
print("Minimum Value:",min_value)
print("Maximum Value:",max_value)

Minimum Value: 31.29
Maximum Value: 266.8884

In [18]:
min_index=df['Item_MRP'].idxmin()
max_index=df['Item_MRP'].idxmax()
print("Minimum Indexvalue:",min_index)
print("Maximum Indexvalue:",max_index)

Minimum Indexvalue: 153
Maximum Indexvalue: 4802

In [22]:
df.iloc[151:154,5:6]

     Item_MRP
151  161.5210
152  197.6426
153   31.2900

In [24]:
#17.value counts - Common category counts will be displayed
Valued_based_counts=df['Item_Type'].value_counts()
Valued_based_counts

Item_Type
Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: count, dtype: int64

In [7]:
#18.unique/nunique
Unique_values=df['Outlet_Size'].unique()
Unique_values

array(['Medium', nan, 'High', 'Small'], dtype=object)

In [8]:
NUnique_values=df['Outlet_Size'].nunique()
NUnique_values

3

In [10]:
#19.Replace/mopfunction
df['Outlet_Location_Type']=df['Outlet_Location_Type'].replace({'Tier 1':'T1','Tier 3':'T3','Tier 2':'T2'})
df['Outlet_Location_Type']

0       T1
1       T3
2       T1
3       T3
4       T3
        ..
8518    T3
8519    T2
8520    T2
8521    T3
8522    T1
Name: Outlet_Location_Type, Length: 8523, dtype: object

In [3]:
# mapping - text to numeric we can use this function
df['Outlet_Size']=df['Outlet_Size'].map({'Medium':1,'small':2,'High':3})
df['Outlet_Size']

0       1.0
1       1.0
2       1.0
3       NaN
4       3.0
       ...
8518    3.0
8519    NaN
8520    NaN
8521    1.0
8522    NaN
Name: Outlet_Size, Length: 8523, dtype: float64

In [8]:
# treatment of duplicate values
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8518    False
8519    False
8520    False
8521    False
8522    False
Length: 8523, dtype: bool

In [9]:
# sum replace numberic values as o - no duplicate and 1 for duplicate present
df.duplicated().sum()

np.int64(0)

In [ ]:
#if duplicate records are found using the below line we can drop those - it shoould be done on approval
df.drop_duplicates(inplace=False)

In [10]:
# nlargest and n smallest records 
df.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [11]:
df.nlargest(5,'Item_MRP')

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
4802,FDS13,6.465,Low Fat,0.125210,Canned,266.8884,OUT017,2007,NaN,Tier 2,Supermarket Type1,1059.9536
5884,FDR25,17.000,Regular,0.139522,Canned,266.8884,OUT046,1997,Small,Tier 1,Supermarket Type1,5034.7796
4159,FDK51,19.850,Low Fat,0.008763,Dairy,266.6884,OUT010,1998,NaN,Tier 3,Grocery Store,264.9884
5254,NCS29,9.000,Low Fat,0.069488,Health and Hygiene,266.6884,OUT013,1987,High,Tier 3,Supermarket Type1,3974.8260
4538,FDS13,NaN,Low Fat,0.217994,Canned,266.5884,OUT019,1985,Small,Tier 1,Grocery Store,1324.9420

In [12]:
df.nsmallest(5,'Item_MRP')

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
153,DRK12,NaN,Low Fat,0.041683,Soft Drinks,31.2900,OUT027,1985,Medium,Tier 3,Supermarket Type3,898.8300
6958,DRK12,9.500,Low Fat,0.041851,Soft Drinks,31.4900,OUT013,1987,High,Tier 3,Supermarket Type1,466.0600
2135,DRK12,9.500,Low Fat,0.042057,Soft Drinks,31.8900,OUT018,2009,Medium,Tier 3,Supermarket Type2,366.1900
2011,FDX59,10.195,Low Fat,0.051618,Breads,31.9558,OUT013,1987,High,Tier 3,Supermarket Type1,373.5138
2242,FDG40,NaN,Low Fat,0.039631,Frozen Foods,31.9558,OUT027,1985,Medium,Tier 3,Supermarket Type3,984.7182

In [13]:
#sample of the dataset - randomly it will pick the no of records speciified
df.sample(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
3933,FDE33,19.350,Regular,0.049594,Fruits and Vegetables,77.0644,OUT013,1987,High,Tier 3,Supermarket Type1,2278.3676
4990,FDE46,18.600,Low Fat,0.015859,Snack Foods,152.9366,OUT017,2007,NaN,Tier 2,Supermarket Type1,453.4098
2892,NCO05,7.270,Low Fat,0.046632,Health and Hygiene,98.4384,OUT049,1999,Medium,Tier 1,Supermarket Type1,1576.6144
6061,FDZ46,7.485,Low Fat,0.069515,Snack Foods,108.7228,OUT017,2007,NaN,Tier 2,Supermarket Type1,1326.2736
6791,FDI34,10.650,Regular,0.085483,Snack Foods,231.4668,OUT018,2009,Medium,Tier 3,Supermarket Type2,3225.1352

In [14]:
# Handling missing data - displays whether the field has null values
df.isnull()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,False,False,False,False,False,False,False,False,False,False,False,False
8519,False,False,False,False,False,False,False,False,True,False,False,False
8520,False,False,False,False,False,False,False,False,False,False,False,False
8521,False,False,False,False,False,False,False,False,False,False,False,False
8522,False,False,False,False,False,False,False,False,False,False,False,False

In [25]:
# displays the count of null values in the particular column
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  8523
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [17]:
# displays the count of not null values in the particular column
df.notnull().sum()

Item_Identifier              8523
Item_Weight                  7060
Item_Fat_Content             8523
Item_Visibility              8523
Item_Type                    8523
Item_MRP                     8523
Outlet_Identifier            8523
Outlet_Establishment_Year    8523
Outlet_Size                  6113
Outlet_Location_Type         8523
Outlet_Type                  8523
Item_Outlet_Sales            8523
dtype: int64

In [19]:
#dropping missing values
df.shape

(8523, 12)

In [ ]:
#df.dropna(inplace = True) - This comment will delete the missing values where ever it has,this commnets should be used on approval 
#df.dropna(axis=0,inplace= True) - This will delete the row, where it has null value
#df.dropna(axis=1,inplace = True) - This will delete the column,where it has null value
#df.dropna(Thresh = 2,inplace =True) - keep rows with atleast 2 non -NaN values

In [24]:
# Filling missing values
df['Item_Weight'] =df['Item_Weight'].fillna(df['Item_Weight'].mean())
df['Item_Weight']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
8518   NaN
8519   NaN
8520   NaN
8521   NaN
8522   NaN
Name: Item_Weight, Length: 8523, dtype: float64

In [26]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  8523
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [27]:
df.notnull().sum()

Item_Identifier              8523
Item_Weight                     0
Item_Fat_Content             8523
Item_Visibility              8523
Item_Type                    8523
Item_MRP                     8523
Outlet_Identifier            8523
Outlet_Establishment_Year    8523
Outlet_Size                  6113
Outlet_Location_Type         8523
Outlet_Type                  8523
Item_Outlet_Sales            8523
dtype: int64

In [30]:
df['Item_MRP']=df['Item_MRP'].mean()
df['Item_MRP']

0       140.992782
1       140.992782
2       140.992782
3       140.992782
4       140.992782
           ...
8518    140.992782
8519    140.992782
8520    140.992782
8521    140.992782
8522    140.992782
Name: Item_MRP, Length: 8523, dtype: float64

In [31]:
# Filling missing values
df['Outlet_Size'] =df['Outlet_Size'].fillna(df['Item_MRP'].mean())
df['Outlet_Size']

0           Medium
1           Medium
2           Medium
3       140.992782
4             High
           ...
8518          High
8519    140.992782
8520         Small
8521        Medium
8522         Small
Name: Outlet_Size, Length: 8523, dtype: object

In [32]:
df.notnull().sum()

Item_Identifier              8523
Item_Weight                     0
Item_Fat_Content             8523
Item_Visibility              8523
Item_Type                    8523
Item_MRP                     8523
Outlet_Identifier            8523
Outlet_Establishment_Year    8523
Outlet_Size                  8523
Outlet_Location_Type         8523
Outlet_Type                  8523
Item_Outlet_Sales            8523
dtype: int64

In [39]:
#group by operation by pandas
df.groupby('Item_Type')['Item_Outlet_Sales'].mean().sort_values(ascending = False)

Item_Type
Starchy Foods            2374.332773
Seafood                  2326.065928
Fruits and Vegetables    2289.009592
Snack Foods              2277.321739
Household                2258.784300
Dairy                    2232.542597
Canned                   2225.194904
Breads                   2204.132226
Meat                     2158.977911
Hard Drinks              2139.221622
Frozen Foods             2132.867744
Breakfast                2111.808651
Health and Hygiene       2010.000265
Soft Drinks              2006.511735
Baking Goods             1952.971207
Others                   1926.139702
Name: Item_Outlet_Sales, dtype: float64

In [ ]:
#combine the data frame - concatenation
df.combined = pd.concat([df1,df2])

#note - should be of same structure

In [ ]:
#combining dataframes - merge - join [inner/left/right/outer]
pd.merge(df1,df2 on='product_id',how='inner')
pd.merge(df1,df2 on='product_id',how='left')
pd.merge(df1,df2 on='product_id',how='right')
pd.merge(df1,df2 on='product_id',how='outer')

In [ ]:
#text method on string data